"""Added tables

Revision ID: 48f448b1af21
Revises: dfb59437855e
Create Date: 2025-03-17 10:52:04.713672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f448b1af21'
down_revision: Union[str, None] = 'dfb59437855e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'culture', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'culture', type_='unique')
    # ### end Alembic commands ###
