"""Change Date in Event_Culture

Revision ID: 653c44d7b995
Revises: dd0d461e6f79
Create Date: 2025-03-21 14:28:45.175879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653c44d7b995'
down_revision: Union[str, None] = 'dd0d461e6f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_culture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('culture_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('mode', sa.Integer(), server_default=sa.text('2'), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['culture_id'], ['culture.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_culture')
    # ### end Alembic commands ###
